debezium.sink.type=rabbitmq
debezium.sink.rabbitmq.connection.host=rabbitmq
debezium.sink.rabbitmq.connection.port=5672
debezium.sink.rabbitmq.connection.username=flash_sale
debezium.sink.rabbitmq.connection.password=flash_sale
debezium.sink.rabbitmq.exchange=orders
debezium.sink.rabbitmq.routingKey=orders
debezium.sink.rabbitmq.autoCreateRoutingKey=false
debezium.sink.rabbitmq.routingKeyDurable=true
debezium.sink.rabbitmq.deliveryMode=2
debezium.sink.rabbitmq.ackTimeout=30000

debezium.format.key=json
debezium.format.key.schemas.enable=false
debezium.format.value=json
debezium.format.value.schemas.enable=false

debezium.source.connector.class=io.debezium.connector.postgresql.PostgresConnector
debezium.source.database.hostname=order-postgres
debezium.source.database.port=5432
debezium.source.database.user=flash_sale
debezium.source.database.password=flash_sale
debezium.source.database.dbname=order_service
debezium.source.topic.prefix=order-service
debezium.source.plugin.name=pgoutput
debezium.source.slot.name=order_service_outbox_slot
debezium.source.publication.name=order_service_outbox_publication
debezium.source.publication.autocreate.mode=filtered
debezium.source.table.include.list=public.outbox_messages
debezium.source.decimal.handling.mode=string
debezium.source.tombstones.on.delete=false
debezium.source.heartbeat.interval.ms=0
debezium.source.snapshot.mode=initial

debezium.source.transforms=outbox
debezium.source.transforms.outbox.type=io.debezium.transforms.outbox.EventRouter
debezium.source.transforms.outbox.table.field.event.id=event_id
debezium.source.transforms.outbox.table.field.event.key=aggregate_id
debezium.source.transforms.outbox.route.by.field=aggregate_type
debezium.source.transforms.outbox.route.topic.replacement=orders
debezium.source.transforms.outbox.table.expand.json.payload=true

debezium.source.offset.storage=org.apache.kafka.connect.storage.FileOffsetBackingStore
debezium.source.offset.storage.file.filename=/debezium/data/offsets.dat
debezium.source.offset.flush.interval.ms=1000
debezium.source.schema.history.internal=io.debezium.storage.file.history.FileSchemaHistory
debezium.source.schema.history.internal.file.filename=/debezium/data/schemahistory.dat
