_format_version: "3.0"

consumers:
  - username: flash-sale-auth
    jwt_secrets:
      - key: __KONG_JWT_ISSUER__
        algorithm: HS256
        secret: __KONG_JWT_SECRET__

services:
  - name: auth-service
    url: __KONG_AUTH_SERVICE_URL__
    routes:
      - name: auth-service-route
        paths:
          - /auth
        strip_path: true

  - name: inventory-service
    url: __KONG_INVENTORY_SERVICE_URL__
    routes:
      - name: inventory-service-read-route
        methods:
          - GET
        paths:
          - /inventory
        strip_path: true
      - name: inventory-service-write-route
        methods:
          - POST
        paths:
          - /inventory
        strip_path: true
        plugins: &authenticated_write_plugins
          - name: jwt
            config:
              key_claim_name: iss
              claims_to_verify:
                - exp
                - nbf
          - name: pre-function
            config:
              access:
                - |
                    __SET_AUTHENTICATED_USER_ID_LUA__

  - name: order-service
    url: __KONG_ORDER_SERVICE_URL__
    routes:
      - name: order-service-route
        methods:
          - POST
        paths:
          - /orders
        strip_path: false
        plugins: *authenticated_write_plugins
